#!/bin/csh
set verbose
set echo

set int    = 700        #first temperature
set intmin = 150        #last temperature
set st_time = 4500      #starting temperature in ps 
set d_code = 21         #density code (number when energy is run)
set folder = `pwd`

while ( ${int} >= ${intmin} )

    cd ${folder}/${int}
    echo ${d_code} | gmx_mpi energy -f ${int}.edr -b ${st_time}
