#!/bin/csh
set verbose
set echo

set init = 21               #initial .gro
set np = 12                 #number of cores to use with mpirun
set folder = `pwd`          #directory where .gro, .mdp, etc.
set input = pvt             #name of the input file .mdp

set int    = 700        #first temperature
set intmin = 150

while ( ${int} >= ${intmin} )
    @ pint = ${int} + 25

    cd ${folder}
    mkdir ${int}
    cp topol.top ${int}/

     
    if ( ${int} == 700 ) then
        cp ${init}.gro ${int}/
        cp ${input}.mdp ${folder}/${int}/${int}.mdp 
        cd ${int}
        sed -i '39d' ${input}.mdp
        sed -i '39d' ${int}.mdp
        sed -i "/^tau_t.*/a ref_t\t\t\= $int" ${int}.mdp  

        gmx_mpi grompp -f npt${int}.mdp -o ${int}.tpr -c ${pint}.gro -r ${init}.gro -p topol.top -n index.ndx
        mpirun -np ${np} gmx_mpi mdrun -v -deffnm ${int}
        @ int -= 25
    else
        cp ${folder}/${pint}/${pint}.gro ${folder}/${int}/${pint}.gro
        cp ${input}.mdp ${folder}/${int}/${int}.mdp 
        cd ${int}
        sed -i '39d' ${int}.mdp
        sed -i "/^tau_t.*/a ref_t\t\t\= $int" ${int}.mdp 

        gmx_mpi grompp -f npt${int}.mdp -o ${int}.tpr -c ${pint}.gro -r ${init}.gro -p topol.top -n index.ndx
        mpirun -np ${np} gmx_mpi mdrun -v -deffnm ${int}
        @ int -= 25
    endif
end







